CREATE DATABASE SPMEDGROUP_2TM_APACHE

USE SPMEDGROUP_2TM_APACHE

CREATE TABLE TIPO_USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE TIPO_ESPECIALIDADE(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE SITUACAO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE CLINICA(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL ,
	ENDERECO VARCHAR (250) NOT NULL ,
	CEP CHAR (250) NOT NULL ,
	HORARIO_FUNCIONAMENTO VARCHAR NOT NULL 
);

alter table clinica alter column HORARIO_FUNCIONAMENTO varchar(250) not null

CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(250) NOT NULL UNIQUE,
	SENHA VARCHAR NOT NULL ,
	DATA_CADASTRO DATETIME NOT NULL ,
	ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO (ID)
);

alter table USUARIO alter column SENHA varchar (250) not null

CREATE TABLE PRONTUARIO(
	ID INT IDENTITY PRIMARY KEY,
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO (ID),
	NOME VARCHAR (250) NOT NULL ,
	CPF CHAR(250) NOT NULL UNIQUE,
	RG CHAR(250) NOT NULL UNIQUE,
	DATA_NASCIMENTO DATETIME NOT NULL,
	ENDERECO VARCHAR (250) NOT NULL,
	TELEFONE VARCHAR(250) NOT NULL
);



CREATE TABLE USUARIO_MEDICO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR (250) NOT NULL ,
	CPF CHAR(250) NOT NULL UNIQUE,
	RG CHAR(250) NOT NULL UNIQUE,
	FACUDADE_FORMACAO VARCHAR (250) NOT NULL ,
	ID_TIPO_ESPECIALIDADE INT FOREIGN KEY REFERENCES TIPO_ESPECIALIDADE (ID),
	CRM CHAR(250) NOT NULL UNIQUE,
	ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA (ID),
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID)	
);


CREATE TABLE CONSULTAS(
	ID INT IDENTITY PRIMARY KEY,
	ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIO(ID),
	DATA_ATENDIMENTO DATETIME NOT NULL ,
	ID_USUARIO_MEDICO INT FOREIGN KEY REFERENCES USUARIO_MEDICO(ID),
	ID_STATUS INT FOREIGN KEY REFERENCES SITUACAO(ID),
	DESCRICAO TEXT NOT NULL
);
